package com.novabank.modelo;


//ENUMERACIÓN USADA PARA INDICAR EL TIPO DE MOVIMIENTO REALIZADO
public enum TipoMovimiento {
    DEPOSITO,
    RETIRO,
    TRANSFERENCIA_SALIENTE,
    TRANSFERENCIA_ENTRANTE
}